attempt to actually run a silent merge conflict

diff --git a/.github/workflows/silent-merge-check.yml b/.github/workflows/silent-merge-check.yml
--- a/.github/workflows/silent-merge-check.yml
+++ b/.github/workflows/silent-merge-check.yml
@@ -93,24 +93,19 @@ jobs:
             fi
 
             # --- Run build/tests ---
-            # git fetch origin pull/$pr/head:pr-$pr
-            # git checkout pr-$pr
-            #
-            # ci_failed=false
-            # ./ci/test_run_all.sh || {
-            #     echo "PR #$pr CI script failed."
-            #     ci_failed=true
-            # }
-            # if [ "$ci_failed" = true ]; then
-            #   conclusion=failure
-            #   summary="CMake build or tests failed."
-            # else
-            #   conclusion=success
-            #   summary="CMake build and tests passed."
-            # fi
+            git fetch origin pull/$pr/head:pr-$pr
+            git checkout pr-$pr
 
-            conclusion=failure
-          summary="Periodic silent merge check has passed! \n\n Details of failure: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
+            if ! output=$(./ci/test_run_all.sh 2>&1); then
+                echo "PR #$pr CI script failed."
+                echo "$output"
+                conclusion=failure
+                summary="Periodic silent merge check has failed. <br><br> Details of failure: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
+            else
+              conclusion=success
+              summary="Periodic silent merge check has passed."
+            fi
+
             # set -o xtrace
             # docker buildx build -t "$CONTAINER_NAME" $DOCKER_BUILD_CACHE_ARG --file "./ci/lint_imagefile" .
             # CIRRUS_PR_FLAG=""
